version: "1.0"
info:
  model: int-scaffold
packages:
- name: Adapters_extProject
  gitServerName: adp
  gitUrl: https://github.com/Sephali-Smrutisikha-IBM-1
  gitUsername: Sephali-Smrutisikha-IBM-1
  gitBranch: main
